### ISSUE TITLE
Nuxtent cannot load pages when @nuxtjs/axios is registered as a module

### ISSUE THREAD

**Issue by brandonpittman** [nuxt-community/nuxtent-module#189]
### Version

[1.4.1](https://github.com/nuxtent-module/releases/tag/1.4.1)

### Reproduction link

[https://github.com/brandonpittman/nuxtent-module/blob/master/examples/multiple-content-types/nuxt.config.js](https://github.com/brandonpittman/nuxtent-module/blob/master/examples/multiple-content-types/nuxt.config.js)

### Steps to reproduce

Add '@nuxtjs/axios' to nuxt.config.js

### What is expected ?

Should display content files

### What is actually happening?

Can't find page

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtent-module/issues/c142">#c142</a>)</em></sub></div>

**Comment by renestalder** [comment]
@brandonpittman Could you elaborate what you mean by "Nuxtent cannot load pages"? Do you have build errors? Do you have run-time errors? What are the error messages?

**Comment by brandonpittman** [comment]
> @brandonpittman Could you elaborate what you mean by "Nuxtent cannot load pages"? Do you have build errors? Do you have run-time errors? What are the error messages?

404s.

**Comment by brandonpittman** [comment]
None of the examples in the repo here have @nuxtjs/axios declared as a module. If you do, you might just see what I mean. I tried it with the example repo, and it did the same thing.

**Comment by renestalder** [comment]
@brandonpittman Ah, okay, I see. I probably never used Axios with it.

Just out of personal curiosity, I would be interested if you have the same problems with Nuxtdown.  
https://github.com/joostdecock/nuxtdown-module

Basically a fork that fixed some major issues and I used that fork for my projects as long as those major issues exist in Nuxtent.

**Comment by joostdecock** [comment]
This is from the top of my head, and I'm on my phone, so take  it with a grain of salt:

If you're using axios in your own project, you need to be careful to keep two different instances with their own configuration. If you mix them up, nuxtent won't be able olto connect to the content-api.

A quick way to check is to open your browser development tools, and check the AJAX requests. Where are they going, and what's the response? That should guide you to where the problem lies.

**Comment by joostdecock** [comment]
Check the API configuration section here: https://github.com/joostdecock/nuxtdown-module/blob/master/README.md#api-configuration

**Comment by brandonpittman** [comment]
nuxtdown has the same problem.

**Comment by renestalder** [comment]
@brandonpittman Thanks for testing.

**Comment by brandonpittman** [comment]
So, are you guys who use Nuxtdown just pulling in Axios on a per-component basis?

**Comment by joostdecock** [comment]
Here's an example of a repo that uses nuxtdown and axios for other things: https://github.com/freesewing/site/blob/develop/nuxt/plugins/fs.js

**Comment by ptdev** [comment]
This is helpful but (imho) it's this module that should be using an isolated instance of the axios configuration instead of having it break the default axios configuration.

As it stands now, if one needs to use the official [@nuxtjs/axios](https://axios.nuxtjs.org/setup) module for other purposes, then setting it up according to the documentation will break the content api.

I think this module should either reuse the axios configuration defined on nuxt.config.js (if available) or ideally just use a completely isolated instance where we can setup every axios parameters in the module's configuration instead of just baseURL and browserBaseURL. 

This would also allow, for example, to be able to change the "content-api" prefix on this module's configuration, which currently isn't possible AFAIK (?).

**Comment by cesasol** [comment]
Is one of the first things I changed when starting the update, there is some progress but is slow. You can see the code on the development branch and is published [here](https://www.npmjs.com/package/@dinamomx/nuxtent) you can install it with npm i --save @dinamomx/nuxtent

**Comment by brandonpittman** [comment]
No one cares about this.
