### ISSUE TITLE
Weird behavior in terminal

### ISSUE THREAD

**Issue by lclaytont** [nuxt-community/nuxtent-module#66]
Hello, 

I am building a site with nuxt and nuxtent. I'm running site with ngrok so I can test the ecommerce portion of my site locally. However, this behavior also exists when I run app on localhost:3000. Posts fetch adequately, but I get the following message in my terminal and am curious as to how I can fix it and will it cause me problems when I generate the static pages?

```nuxt:render Rendering url /_nuxt/1e316f558f6d86bcdc7a.hot-update.json +0ms
  TypeError: app.$content is not a function
  
  - _post.7837411e44d2052b889d.js:88 Object._callee$
    pages/_post.7837411e44d2052b889d.js:88:26
  
  - asyncToGenerator.js:17 step
    node_modules/babel-runtime/helpers/asyncToGenerator.js:17:0
  
  - server-bundle.js:422 
    server-bundle.js:422:14
  
  - server-bundle.js:401 
    server-bundle.js:401:12
  
  - _post.7837411e44d2052b889d.js:105 asyncData
    pages/_post.7837411e44d2052b889d.js:105:20
  
  - utils.js:138 promisify
    .nuxt/utils.js:138:14
  
  - server-bundle.js:1274 
    server-bundle.js:1274:96
  
  - server.js:167 Object._callee$
    .nuxt/server.js:167:48```

**Comment by medfreeman** [comment]
Isn't this a duplicate / related to #57 ?

**Comment by alidcastano** [comment]
Hi @lclaytont What version of Nuxtent are you using? I've added guards to prevent this behavior. The problem is that when you start a nuxt/nuxtent site and have previous tabs open, the content will be fetched for those tabs as well due to hot module reloading. 

Regardless, this won't cause any problems during site generation. The problem is only during `npm run dev` due to hot module reloading as described above.
