### ISSUE TITLE
feature request: slots in markdown components

### ISSUE THREAD

**Issue by cesasol** [nuxt-community/nuxtent-module#85]
It's awesome that components are back, but sometimes props are not enough so, it is posible to have slots? Like:
``` markdown
@[testimonio](persona="Paco sanchez")

[^testimonio]: Slot without name

[^testimonio]("title"): Slot with name 

[^testimonio]("content" multiline):
# Slot with multiline enabled

| Data | Cuantity | Cualify |
| --- | --- | --- |
| 0 | 2 | true|

> This is a nice and short blockquote

[/testimonio]
```

The `^` is inspired from the [footnote](http://cheatsheet.aboutmde.org/#footnote) from markdown extended, and the closing bracket from wordpress shortcodes

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-module/issues/c73">#c73</a>)</em></sub></div>

**Comment by alidcastano** [comment]
What's your use case for this? I can see why this would be required in the markdown, I just don't see it being used too often to justify the added complexity.

Thanks for proposing a syntax. 

Ideally, I would like to keep it consistent. So all components start with `@[componentName]`.

Maybe a syntax similar to handlebars could work:

```
@[#componentName](prop="someProp")
    some slot goes here
[/componentName]
```

Where `@[]` marks a component and `#` slot opening and `/` slot closing.  (Though using both `@` and `#` feels clunky.)

@medfreeman Thoughts?

**Comment by cesasol** [comment]
In my use case is for profiles  and testimonials elements, where some markdown would be useful. Also I believe that with this addon on nuxt we can build websites with almost all the content in the md files.
Another approach and is the one that I took is to have that content that would be on the slot called with ajax on the mounted component. But is not really a concise way since the `$content` method is not available outside `asyncData` so axios is used directly.
About the syntax your approach is way better maybe the `#` could be complemented with a colon at the end of the component definition, and a named slot could be like this:
```md
@[#componentName](prop="someProp"):titleslot
    # title slot goes here
[/componentName]
```

**Comment by alidcastano** [comment]
Yes, I could see how slots would be useful. I'll keep the issue open so it could be added once we stabilize current features. 

Proposed syntax: 

```
@[#componentName](prop="someProp"):slotName
    slot goes here 
[/componentName]
```

**Comment by cesasol** [comment]
Update on this, I just implemented but using the fork from @joostdecock so the merge would bring all the changes from his fork and the api changed a bit:

``` md
@[#Some/ComponentName]

Some cool content

@[/Modelos/SectionHero]

```

And for slots I think is better to leave the original vue implentation since markdown doesn't touch html

``` markdown
@[#Modelos/SectionHero]

<div slot="head">

# More markdown on the head slot

</div>

| markdown | on | the |
| --- | --- | --- |
| default | slot | yea! |

@[/Modelos/SectionHero]
```

Here is the link to the [branch](https://github.com/dinamomx/nuxtent-module/tree/feature/slots)

**Comment by joostdecock** [comment]
I'd be happy to see things merged upstream, and consolidate our efforts :)

**Comment by cesasol** [comment]
@joostdecock  Just a question before sending the PR, should I keep the branding nuxtdown from your fork or try reverse all the nuxtdown appareances to nuxtent and restore the readme

**Comment by joostdecock** [comment]
The reason I changed the name is because I wanted/needed to publish my fork on NPM because I'm using it in production in one of my projects.
There's no real reason like that in nuxtent, so changing things back makes sense, but there are two things to keep in mind:

**Minor: Documentation**

The nuxtdown README is the only place the new functionality is documented. If we put the original README back, the info in it won't match up with the reality.

**Less minor: Maintaining nuxtent**

@alidcastano has been honest about the fact that it is becoming increasingly difficult for him to find the time to maintain Nuxtent. I've indicated a willingness to help out, but I've also said that I am not comfortable to take over the entire thing on my own as I'm afraid it's a bit above my current skill level.

So the question is, what happens when you submit a PR? Who is going to merge it? Because doing so will break the configuration of a bunch of existing installs. And if we do, who will update the documentation? Who knows how it's build?

I'm still willing to work on this, but I feel we need a plan if we want to secure a sustainable future for Nuxtent, as right now it is de-facto unmaintained.

**Comment by cesasol** [comment]
@joostdecock for my part, I feel like you, I have no experience in the management of an open source project. But I just talked to my boss @ramjamx and we agree to keep mantaining this project as a company since we use it on almost any website we create and feel we owe something to the community.

I think we can start with the project documentation and make the changes compatible with previous versions. 

I propose to make the PR to the development branch as we complete this tasks.

**Comment by joostdecock** [comment]
Cool. Let's do this :)

**Comment by apmontgomery** [comment]
Great to hear, both of you.  I'm also happy to put some time in this week to help out.

**Comment by cesasol** [comment]
Ready for testing on the development branch
