### ISSUE TITLE
newbie questions

### ISSUE THREAD

**Issue by magick93** [nuxt-community/nuxtent-module#86]
Hello

I've been reviewing static site generators with the aim of finding something for generating documentation. 

**Nuxtjs** and **nuxtend-module** look really interesting!

I have a few questions I hope you can help with.

**Navigation**

I am completely new to VueJs - so please forgive me if this is a stupidly simple question. I understand that, to add new pages (or content) I simply put a new `.md` file in the content directory. This is very simple. How can I then create a navigation system for these documents?

**Exporting Static content**

I understand I can export a static site. But I could not find how to do this. Can you please clarify this?

**Export as custom format**

Is it possible to export in another format besides html? I have been trying Hugo and one nice feature is all of the different formats it supports. On use case I am looking for is to be able to export json or yaml. I am wanting to document various micro services and would like to be able to export certain settings as json or yaml - using a template - so that the resulting file can be used as a deployment config in OpenShift. Is such a thing possible?

Thanks and regards

**Comment by alidcastano** [comment]
Navigation: Every page has a `path` property. So you can automate the navigation by fetching all pages and creating links with their path. Also, you have access to page `anchors` (headings inside page), so you can use those for within-page navigation if the content page is long. (For a reference, here's the [content navigation example](https://github.com/nuxt-community/nuxtent-module/blob/master/examples/content-navigation/pages/guide.vue#L5).)

Exporting site: Since the latest release, @medfreeman made it so that you just run `nuxt generate`. Your site will be available in `dist` folder and all content files will be generated for you. 👍 

Custom formats: Are you refering to the generation of content files or of the entire site? We generate the content files as `json` data so that they can be seamlessly used within nuxt pages. We do this because our primary concern is to integrate with Nuxt so that the API is simple, with minimal overhead. As for custom generation of the actual site (i.e. pages), Nuxt handles that.

If I answered all your questions, feel free to close this! And thanks again for using nuxtent!

**Comment by magick93** [comment]
Thanks @alidcastano 

The navigation example you gave is like a Table of Contents? This will be very useful.
But what I am stuck on is how to present a list of all documents. I realize I can just type the path in the browser. But users who want to view the site will not know what documents are available.

I appreciate this is probably very basic, however I - and the users who will be adding docs - are more content creators than vue developers.

> Custom formats: Are you refering to the generation of content files or of the entire site?
Im interested in both. But exporting the whole site to html is completely sufficient.

However, it would be really useful if it was possible to export certain page data (in Hugo lingo its called `front matter`) using some kind of template. In the same way that vue templates use html tags, is it possible to have another *view* that could export data as say yaml or json - depending on a vue template?

**Comment by alidcastano** [comment]
A list of all documents works in a similar way - just iterate through the fetched content pages:
```
asyncData: async ({ app }) => ({
    articles: await app.content('/articles').getAll()
})
```

`articles` will be an array of content pages that you can iterate through and render as you please.


---

Can you define what you mean by export? As far as I'm aware, `front-matter` works to specify/override page data and Nuxtent supports this. Are you asking to allow different types of front-matter in markdown files? Right now we only support yaml front matter. But if you like you can open new issue with feature request. 

Closing this since questions have been answered.
