### ISSUE TITLE
browser url incorrectly points to content-api

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/nuxtent-module#88]
related to comment in #83

**Comment by alidcastano** [comment]
The problem is that binaries were removed, so you have to set `STATIC=true` in command so that url can be set appropritely. 

Then it works:

```
nuxt:axios BaseURL: http://localhost:3000/content-api (Browser: /_nuxt/content)
```

Right now there's a problem without using binaries (see #89). I'll wait until resolving that before figuring out how to let users specify that they are using a static site. 

Note: Ideally, if baseURL is empty we should just make static the default, since most apps will need to specify baseURL for content-api.

**Comment by josh--** [comment]
just dropping this by because i think its related to this and issue #83.
 
previously i opened a ticket that was throwing the same type of errors. 

https://github.com/nuxt-community/nuxtent-module/issues/47

you had added a new param that when used in the main configuration. would allow the generated site to work correctly. The reason was because the environmental variable is not available, in the browsers context when hosting as a plain static site.

**Comment by alidcastano** [comment]
Yes `isStatic` in config and `process.env.STATIC` will both have to be fixed, thanks for bringing this up

**Comment by josh--** [comment]
no prob, i was just taking a quick peek. Something like this should do it (https://www.npmjs.com/package/envify). idk if thats the best fit or not but something along those lines might help.
