### ISSUE TITLE
OPEN http://localhost:3000 locally during the generate process

### ISSUE THREAD

**Issue by STnetwork** [nuxt-community/nuxtent-module#93]
Before with the latest versions we needed to open locally the content-api `OPEN http://localhost:3000` for the generate process, is it normal that now there isn't it at all during the generate process ?

**Comment by alidcastano** [comment]
@medfreeman has been working on getting rid of `nuxtent generte` so that we don't have to support our own binaries and the codebase could be simpler. 

Thank you for reporting this issue (and #92). They are in fact due to that change and we will work to get it resolved by next release. Thank you again for your patience and help

**Comment by STnetwork** [comment]
Ok good news so !

When the module will be completely operating it will be very interesting ;)

**Comment by alidcastano** [comment]
Almost there :)

**Comment by medfreeman** [comment]
Thanks ! Is this an actual error, or is it just missing the `OPEN http://localhost:3000` log message ?
I thought of it while doing the fixes yesterday, but had not so much time in front of me.

**Comment by STnetwork** [comment]
@medfreeman I think because of this, all pages aren't generated, only root pages are generated, but no error messages.

**Comment by medfreeman** [comment]
@stnetwork that's because in 'generate' mode, the server is generated directly through express in nuxtent code, instead of nuxt connect instance, and i don't display a message as nuxt does.
I'll add the same 'OPEN' log message for consistency.
#92 is another problem that i tracked down a moment ago. I'll release the fix when back on computer in an hour or two.

**Comment by alidcastano** [comment]
I don't think the message is necessary. It caused confusion before (opening localhost versus deployment url) and Nuxtent abstracts that away so user doesn't have to be aware that server is running to generate all content files.

**Comment by STnetwork** [comment]
@medfreeman  Ok apparently it's right I missed something in my nuxtent.config, it generates all pages !

I don't know what do you use for an environment test static but, maybe you should use [surge](https://surge.sh/) for that , it's free, easy and fast to deploy a static site.

you just need to do : 
`[root@stnetwork]$  cd dist/
`
`[root@stnetwork dist]$  surge`


For the moment I have this result : 

[stnetwork.surge.sh](http://stnetwork.surge.sh)

**Comment by medfreeman** [comment]
@STnetwork the tests only cover the local part of `generate` part by launching a local express instance at the moment, and verifying the returned pages content, which is sufficient for this kind of testing.
And a distant test can also be mocked, which is probably better, covering the fact that there's a user `baseUrl` option specified, then mocking the distant server to avoid complicating the test environment.

**Comment by medfreeman** [comment]
@alidcastano so you'd go for removing the `OPEN` message in every case ?
I'll also have to look if it possible or not.

**Comment by alidcastano** [comment]
Closing due to inaction, please feel free to open up a new issue if the `OPEN` message still bothers you. And PRs are also always welcome!
