### ISSUE TITLE
request: remove API logging messages in production 

### ISSUE THREAD

**Issue by programmerby** [nuxt-community/nuxtent-module#95]
I still see nuxtent messages after `nuxt build` and `nuxt start`:
```
/content-api GET http://localhost:3000/
   Response sent successfully.
```
Why?

**Comment by medfreeman** [comment]
1. After `nuxt build`, it is normal, after all your content is served from localhost and need to be read from somewhere to be integrated in the build.
After `nuxt start`, the reason is it that in its current state nuxtent only fetches generated files (from `/_nuxt/content/` folder) in `static` mode (`nuxt generate`).
That behavior could be discussed and possibly changed to fetch static files in `production` (`nuxt build`).

2. About the fact that the messages are logged, i actually think it is a good thing because it exposes how and when content is fetched.

**Comment by alidcastano** [comment]
Logging should have the option of being optionally turned on/off as  not everyone wants to have it on in production

**Comment by dahrens** [comment]
Just digged through the current configuration in `module.js` - looks like it makes sense to wait, until the refactored code from https://github.com/nuxt-community/nuxtent-module/pull/108 is done and got merged.

**Comment by alidcastano** [comment]
Sounds good 👍

**Comment by mgrandl** [comment]
So what's the state on this? Since the PR never got merged, is there any option to disable this obnoxious logging?

**Comment by besnikh** [comment]
@ALL any update on this ?

**Comment by Skriptach** [comment]
I have find this topic by googling. I need feature be able to choose log level detalization. Cuz I do not need to duplicate [read consume disc space] this requests in log. I already have access.log from nginx
